title: <p align="center"> Lakshminarayanan Narayanan </p>
logo: /assets/img/logo.png

description:
  <p align="center"> |
  <a href="https://www.linkedin.com/in/surya67/">LinkedIn</a> |
  <a href="https://github.com/lakshminarayann">GitHub</a>
  
  <br>   
  I'm working as Product Developer.
  <br>
  </p>



theme: jekyll-theme-minimal
